# Generated by Django 4.1.4 on 2022-12-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='default', max_length=128),
            preserve_default=False,
        ),
    ]
