# Generated by Django 4.1.4 on 2022-12-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='wordCount',
            field=models.IntegerField(default=0),
        ),
    ]
